services:
  db:
    image: mysql:8.0.31
    container_name: db
    hostname: db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
    ports:
      - ${DB_PORT}:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 0s